#!/usr/bin/env bash
# Function to display subdomain information
display_info() {
    local domain=$1
    local subdomain=$2
    local record_type=""
    local destination=""

    if [ -n "$subdomain" ]; then
        record_type=$(dig +short $subdomain.$domain | awk '{print toupper($1)}')
        destination=$(dig +short $subdomain.$domain)
    fi

    echo "The subdomain $2 is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=($subdomain)
fi

for sub in "${subdomains[@]}"; do
    display_info $1 $sub
done
