#!/usr/bin/env bash
# Function to display subdomain information
display_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$(dig +short "${2}"."$1" | awk '{print toupper($1)}')
    local destination=$(dig +short "${2}"."$1")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=($subdomain)
fi

for sub in "${subdomains[@]}"; do
    display_info $domain $sub
done
