#!/usr/bin/env bash
# Install Nginx and set custom HTTP response header
sudo apt-get update
sudo apt-get install -y nginx

hostname = $(hostname)

sudo bash -c "cat > /etc/nginx/sites-available/default" <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
        add_header X-Served-By $hostname;
    }
}
EOF

sudo systemctl restart nginx
