#!/usr/bin/env bash
# Install Nginx and set custom HTTP response header
sudo apt-get update
sudo apt-get install -y nginx

hostname = $(hostname)

sudo bash -c "cat > /etc/nginx/sites-available/default" <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        return 200 "Hello World\n";
        add_header X-Served-By $hostname;
    }

    location /redirect_me {
        return 301 http://example.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        return 404 "Ceci n'est pas une page\n";
        add_header X-Served-By $hostname;
    }

    add_header X-Served-By $hostname;
}
EOF

sudo bash -c 'echo "Ceci n'est pas une page" > /var/www/html/404.html'

sudo systemctl restart nginx
