#!/bin/bash
# Get the contents of the current directory
contents=$(ls -1 .)

# Loop through each item in the contents list
for item in $contents
do
	  # Display the item name
	    echo $item
    done
