#!/usr/bin/env bash
# Display Best School then Hi
counter=1
while [ $counter -le 10 ]
do
    if [[ $counter -eq 9 ]]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
