#!/usr/bin/env bash
# change user in nginx user configuration
apt-get update -y
apt-get install nginx -y
chmod 644 /etc/nginx/nginx.conf
# change user
sed -i 's/user\s\+\w\+/user nginx/' /etc/nginx/nginx.conf
# update configuration to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
