#!/usr/bin/env bash
# change user in nginx user configuration
apt-update
apt-get install nginx -y
useradd -r nginx
sudo chmod 644 /etc/nginx/nginx.conf
# change user
sudo sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
# update configuration to listen on port 8080
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
